# Generated by Django 3.2.4 on 2021-07-01 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('class_number', models.IntegerField()),
                ('auth', models.IntegerField()),
                ('joined_date', models.DateTimeField()),
                ('last_login_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('student_number', models.IntegerField()),
                ('joined_date', models.DateTimeField()),
                ('last_login_date', models.DateTimeField()),
                ('homeroom_teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.teacher')),
            ],
        ),
    ]
