# Generated by Django 3.2.4 on 2021-07-01 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='homeroom_teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='account.teacher'),
        ),
    ]
