# Generated by Django 3.2.4 on 2021-06-03 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('clsNum', models.IntegerField()),
                ('name', models.CharField(max_length=5)),
            ],
        ),
    ]
