# Generated by Django 3.2.4 on 2021-06-09 03:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountTch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=5)),
                ('Auth', models.IntegerField(default=1)),
                ('joined_date', models.DateField(default=django.utils.timezone.now)),
                ('last_login', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stuNum', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=5)),
                ('joined_date', models.DateField(default=django.utils.timezone.now)),
                ('last_login', models.DateField(default=django.utils.timezone.now)),
                ('isAdmin', models.CharField(default='0', max_length=1)),
                ('isSuperUser', models.CharField(default='0', max_length=1)),
                ('tch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.accounttch')),
            ],
        ),
    ]
