# Generated by Django 3.2.4 on 2021-06-03 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='pw',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
