# Generated by Django 3.2.4 on 2021-06-08 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='clsNum',
            field=models.IntegerField(unique=True),
        ),
    ]
