# Generated by Django 3.2.4 on 2021-06-08 03:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='joined_date',
            field=models.DateField(default=datetime.datetime(2021, 6, 8, 12, 27, 28, 600667)),
        ),
        migrations.AddField(
            model_name='account',
            name='last_login',
            field=models.DateField(default=datetime.datetime(2021, 6, 8, 12, 27, 28, 600667)),
        ),
    ]
