# Generated by Django 3.2.4 on 2021-06-08 03:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210608_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='joined_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_login',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
