# Generated by Django 3.2.4 on 2021-06-11 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_account_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounttch',
            name='teacher_id',
            field=models.CharField(default='id', max_length=20, unique=True),
        ),
    ]
