# Generated by Django 3.2.4 on 2021-06-08 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210608_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='isAdmin',
            field=models.CharField(default='0', max_length=1),
        ),
        migrations.AddField(
            model_name='account',
            name='isSuperUser',
            field=models.CharField(default='0', max_length=1),
        ),
    ]
