# Generated by Django 3.2.4 on 2021-06-15 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_accounttch_teacher_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='stuNum',
            field=models.IntegerField(),
        ),
    ]
