# Generated by Django 3.2.4 on 2021-06-09 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210609_0232'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='tch',
            field=models.CharField(default='', max_length=5),
        ),
    ]
