# Generated by Django 3.2.4 on 2021-06-15 15:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_account_stunum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttch',
            name='Auth',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='accounttch',
            name='joined_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='accounttch',
            name='last_login',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
