# Generated by Django 3.2.4 on 2021-06-16 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210616_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounttch',
            name='class_number',
            field=models.IntegerField(default=0),
        ),
    ]
