# Generated by Django 3.2.4 on 2021-07-01 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_accounttch_class_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='AccountTch',
        ),
    ]
