# Generated by Django 3.2.4 on 2021-07-04 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='result',
        ),
        migrations.AddField(
            model_name='subject',
            name='second_period',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='second_result',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='third_period',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='third_result',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
