# Generated by Django 3.2.4 on 2021-07-05 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0002_auto_20210704_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='second_result',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='third_result',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
