# Generated by Django 3.2.4 on 2021-07-06 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_user_homeroom_teacher'),
        ('subject', '0005_subject_third_result_second'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='second_period',
            new_name='period',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='second_result',
            new_name='result',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='third_period',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='third_result',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='third_result_second',
        ),
        migrations.AddField(
            model_name='subject',
            name='year',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='subject',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.user'),
        ),
    ]
