# Generated by Django 3.2.4 on 2021-07-01 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0005_teacher_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='survey',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('survey_name', models.CharField(max_length=45)),
                ('opened_date', models.DateField()),
                ('closed_date', models.DateField()),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='third_select',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first', models.CharField(max_length=45, null=True)),
                ('second', models.CharField(max_length=45, null=True)),
                ('third', models.CharField(max_length=45, null=True)),
                ('four', models.CharField(max_length=45, null=True)),
                ('five', models.CharField(max_length=45, null=True)),
                ('survey_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='survey.survey')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.user')),
            ],
        ),
        migrations.CreateModel(
            name='second_select',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first', models.CharField(max_length=45, null=True)),
                ('second', models.CharField(max_length=45, null=True)),
                ('third', models.CharField(max_length=45, null=True)),
                ('four', models.CharField(max_length=45, null=True)),
                ('five', models.CharField(max_length=45, null=True)),
                ('survey_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='survey.survey')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.user')),
            ],
        ),
    ]
